// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwpstjzwgsofrlgpqtpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3cHN0anp3Z3NvZnJsZ3BxdHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzUyMDAsImV4cCI6MjA1NzU1MTIwMH0.bFjEJ2Vgft0SPZ5F4gD6sENMWnwujVF9UXET_t5uGGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);